version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Checking inside index.html
      - tests/check_orange.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
